name: fisikamu
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.7
  google_sign_in: ^5.1.1
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  http: ^0.13.3
  uuid: ^3.0.4
  provider: ^6.0.0
  cached_network_image: ^3.1.0
  flutter_html: ^2.1.1
  flutter_tex: ^4.0.3+1
  carousel_slider: ^4.0.0
  flutter_local_notifications: ^8.2.0
  rxdart: ^0.27.2
  video_player: ^2.2.0
  chewie: ^1.1.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^0.22.0
  skeleton_loader: ^2.0.0+4
  google_fonts: ^2.1.1
  webview_flutter_plus: ^0.2.3+1
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/googleLogo.png
    - assets/images/home_icon.png
    - assets/images/home_icon_gray.png
    - assets/images/home_red.svg
    - assets/images/home_gray.svg
    - assets/images/tryout_red.svg
    - assets/images/tryout_gray.svg
    - assets/images/tryOut_icon.png
    - assets/images/tryOut_icon_gray.png
    - assets/images/video_icon.png
    - assets/images/video_icon_gray.png
    - assets/images/text_icon.png 
    - assets/images/text_icon_gray.png
    - assets/images/pendahuluan_icon.png
    - assets/images/mekanika_icon.png
    - assets/images/fismod_icon.png
    - assets/images/fluida_icon.png
    - assets/images/getaran&gelomabng_icon.png
    - assets/images/listrik_icon.png
    - assets/images/magnet_icon.png
    - assets/images/optik_icon.png
    - assets/images/quantum_icon.png
    - assets/images/Termo_icon.png
    - assets/images/notification.png
    - assets/images/userPhotoPlaceholder.png
    - assets/images/PlayVideo.png
    - assets/images/empty.png
    - assets/images/empty.svg
    - assets/images/logo apps.png
    - assets/images/logoWhite.png
    - assets/images/fast-forward-double-right-arrows-symbol.png
    - assets/images/left.png
    - assets/images/Logo1.svg
    - assets/images/Logo2.svg
    - assets/images/Logo3.svg
    - assets/images/Logo4.svg
    - assets/images/logo_video.svg
    - assets/images/vektor.svg
    - assets/images/mekanika.svg
    - assets/images/fluida.svg
    - assets/images/getaran.svg
    - assets/images/termo.svg
    - assets/images/listrik.svg
    - assets/images/magnet.svg
    - assets/images/optik.svg
    - assets/images/fismod.svg
    - assets/images/kuantum.svg
    - assets/images/teks gray.svg
    - assets/images/video red.svg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
